# slam_toolbox:
#   ros__parameters:
#     # Plugin params
#     solver_plugin: solver_plugins::CeresSolver
#     ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
#     ceres_preconditioner: SCHUR_JACOBI
#     ceres_trust_strategy: LEVENBERG_MARQUARDT
#     ceres_dogleg_type: TRADITIONAL_DOGLEG
#     ceres_loss_function: None

#     # ROS Parameters
#     odom_frame: odom
#     map_frame: map
#     base_frame: base_link
#     scan_topic: /scan
#     # mode: mapping
#     mode: localization

#     debug_logging: false
#     throttle_scans: 1
#     transform_publish_period: 0.02 # if 0 never publishes odometry
#     map_update_interval: 1.0
#     resolution: 0.02
#     min_laser_range: 0.3 # Sửa lỗi phạm vi tối thiểu của LiDAR
#     max_laser_range: 12.0 # Sửa lỗi phạm vi tối đa của LiDAR
#     minimum_time_interval: 0.5
#     transform_timeout: 0.2
#     tf_buffer_duration: 30.
#     stack_size_to_use: 40000000
#     enable_interactive_mode: true
#     map_file_name: /home/phuocquyen/real_robot/map/my_map_serial
#     map_start_at_dock: true

#     # General Parameters
#     use_scan_matching: true
#     use_scan_barycenter: true
#     minimum_travel_distance: 0.5 #
#     minimum_travel_heading: 0.5
#     scan_buffer_size: 10
#     scan_buffer_maximum_scan_distance: 10.0
#     link_match_minimum_response_fine: 0.1
#     link_scan_maximum_distance: 1.5
#     loop_search_maximum_distance: 3.0
#     do_loop_closing: true
#     loop_match_minimum_chain_size: 10
#     loop_match_maximum_variance_coarse: 3.0
#     loop_match_minimum_response_coarse: 0.35
#     loop_match_minimum_response_fine: 0.45

#     # Correlation Parameters - Correlation Parameters
#     correlation_search_space_dimension: 0.5
#     correlation_search_space_resolution: 0.01
#     correlation_search_space_smear_deviation: 0.1

#     # Correlation Parameters - Loop Closure Parameters
#     loop_search_space_dimension: 8.0
#     loop_search_space_resolution: 0.05
#     loop_search_space_smear_deviation: 0.03

#     # Scan Matcher Parameters
#     distance_variance_penalty: 0.5
#     angle_variance_penalty: 1.0

#     fine_search_angle_offset: 0.00349
#     coarse_search_angle_offset: 0.349
#     coarse_angle_resolution: 0.0349
#     minimum_angle_penalty: 0.9
#     minimum_distance_penalty: 0.5
#     use_response_expansion: true

slam_toolbox:
  ros__parameters:
    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    # mode: mapping
    mode: localization

    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.02
    map_update_interval: 0.01 #0.01
    resolution: 0.02 #0.02
    transform_tolerance: 0.5
    min_laser_range: 0.3 #0.3
    max_laser_range: 12.0
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.
    stack_size_to_use: 40000000
    enable_interactive_mode: true
    map_file_name: /home/huuhoa/hospital_robot/src/hospital_package/maps/my_map_serial
    map_start_at_dock: true

    # # General Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.3 # Giảm từ 0.5 xuống 0.3
    minimum_travel_heading: 0.3 # Giảm từ 0.5 xuống 0.3
    scan_buffer_size: 20 #10
    scan_buffer_maximum_scan_distance: 12.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0 # Giảm từ 5.0 xuống 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 5 # Giảm từ 10 xuống 5
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.3 # Giảm từ 0.35 xuống 0.3
    loop_match_minimum_response_fine: 0.4 # Giảm từ 0.45 xuống 0.4

    # Correlation Parameters - Correlation Parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01 #0.01
    correlation_search_space_smear_deviation: 0.1

    # Correlation Parameters - Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05 #0.05
    loop_search_space_smear_deviation: 0.03

    # Scan Matcher Parameters
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0

    fine_search_angle_offset: 0.00698 # Tăng từ 0.00349 lên 0.00698
    coarse_search_angle_offset: 0.698 # Tăng từ 0.349 lên 0.698
    coarse_angle_resolution: 0.0698 # Tăng từ 0.0349 lên 0.0698
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
